jobs:
    include:
        - stage: Tests
          script: echo "`date` Unit Tests" && sleep 5
          name: "Unit Tests"
        - script: echo "`date` Integration-tests" && sleep 6
          name: "Integration-tests"
        - stage: deplay
          name: "Deplay to GCP"
          script: echo "`date` Deplay to GCP"